language: ruby
rvm:
  - 2.2
  - jruby
cache: bundler
branches:
  only:
  - main
before_install:
  - gem install jekyll
  - gem install bundler -v 2.0.1
  - bundle update jekyll
  - bundle lock --add-platform universal-java-11
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  repo: rajendraarora16/blogs.github.io
  provider: pages
  local-dir: ./site
  target-branch: main
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: false 
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
